spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres2
    username: postgres
    password: 2255
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

url : https://api.opensensemap.org/boxes?model=homeWifi
